global:
  scrape_interval: 2s

scrape_configs:
  - job_name: vllm
    metrics_path: /metrics
    static_configs:
      - targets: ['vllm:8000']

  - job_name: dcgm
    metrics_path: /metrics
    static_configs:
      - targets: ['dcgm-exporter:9400']
